name: Maya-Builder

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Ubuntu:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update
      - name: Build Maya
        run: cd Maya && platformio run

      - name: create_release
        uses: svenstaro/upload-release-action@v1-release
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            file: Maya\.pio\build\*\firmware.bin
            tag: ${{ github.ref }}
            overwrite: true
             
            
            
      

  